# --- !Ups

create table countries (
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name  varchar(255),
   constraint pk_countries primary key (id)
);

# --- !Downs

drop table if exists countries;