# --- !Ups

ALTER TABLE tags_map DROP COLUMN entity_type;
ALTER TABLE tags ADD COLUMN type VARCHAR(100);

UPDATE tags SET type = 'SERIES' WHERE name IN ('WORLD_CUP', 'IPL', 'CHAMPIONS_TROPHY', 'BBL', 'ILT20', 'CHAMPIONS_LEAGUE', 'ASIA_CUP', 'WTC', 'CPL');
UPDATE tags SET type = 'MATCH' WHERE name IN ('FINAL', 'SEMI_FINAL', 'QUARTER_FINAL', 'KNOCKOUT', 'ELIMINATOR', 'THIRD_PLACE', 'QUALIFIER', 'QUALIFIER_1', 'QUALIFIER_2', 'CHALLENGER');

ALTER TABLE tags ALTER COLUMN type SET NOT NULL;

# --- !Downs

ALTER TABLE tags DROP COLUMN type;
ALTER TABLE tags_map ADD COLUMN entity_type VARCHAR(100) NOT NULL;