# --- !Ups

CREATE TABLE partnerships (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    innings             SMALLINT NOT NULL,
    wicket              SMALLINT NOT NULL,
    runs                SMALLINT NOT NULL,
    balls               SMALLINT NOT NULL,
    ended               BOOLEAN NOT NULL,
    match_player_id_1   INTEGER NOT NULL,
    runs_1              SMALLINT NOT NULL,
    balls_1             SMALLINT NOT NULL,
    match_player_id_2   INTEGER NOT NULL,
    runs_2              SMALLINT NOT NULL,
    balls_2             SMALLINT NOT NULL,
    primary_entry       BOOLEAN NOT NULL,
    CONSTRAINT pk_partnerships PRIMARY KEY (id),
    CONSTRAINT fk_p_match_player_1 FOREIGN KEY (match_player_id_1) REFERENCES match_player_map (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_p_match_player_2 FOREIGN KEY (match_player_id_2) REFERENCES match_player_map (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uk_p_players_innings_primary_wicket UNIQUE (match_player_id_1, match_player_id_2, innings, wicket)
);

# --- !Downs

DROP TABLE partnerships;