# --- !Ups

CREATE TABLE ballwise_details (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batsman_match_player_id     INTEGER NOT NULL,
    bowler_match_player_id      INTEGER NOT NULL,
    innings                     SMALLINT NOT NULL,
    ball                        SMALLINT NOT NULL DEFAULT 0,
    dismissal                   BOOLEAN NOT NULL,
    total_runs                  SMALLINT NOT NULL DEFAULT 0,
    batsman_runs                SMALLINT NOT NULL DEFAULT 0,
    bowler_runs                 SMALLINT NOT NULL DEFAULT 0,
    extras_runs                 SMALLINT NOT NULL DEFAULT 0,
    extras_type                 VARCHAR(100),
    timestamp                   BIGINT NOT NULL,
    CONSTRAINT pk_ballwise_details PRIMARY KEY (id),
    CONSTRAINT uk_bd_timestamp UNIQUE (timestamp),
    CONSTRAINT fk_bd_batsman
        FOREIGN KEY (batsman_match_player_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_bd_bowler
        FOREIGN KEY (bowler_match_player_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_ballwise_details_batsman ON ballwise_details(batsman_match_player_id);
CREATE INDEX idx_ballwise_details_bowler ON ballwise_details(bowler_match_player_id);

# --- !Downs

DROP TABLE ballwise_details;