# --- !Ups

INSERT INTO `tags` (`name`) VALUES
('FINAL'),
('SEMI_FINAL'),
('QUARTER_FINAL'),
('KNOCKOUT'),
('ELIMINATOR'),
('THIRD_PLACE'),
('QUALIFIER_1'),
('QUALIFIER_2');

# --- !Downs

DELETE FROM `tags` WHERE `name` IN (
'FINAL',
'SEMI_FINAL',
'QUARTER_FINAL',
'KNOCKOUT',
'ELIMINATOR',
'THIRD_PLACE',
'QUALIFIER_1',
'QUALIFIER_2'
)