# --- !Ups

CREATE TABLE stadiums (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name         VARCHAR(200) NOT NULL,
  city         VARCHAR(100) NOT NULL,
  state        VARCHAR(100),
  country_id   BIGINT NOT NULL,
  CONSTRAINT pk_stadiums PRIMARY KEY (id),
  CONSTRAINT uk_s_name_country_city UNIQUE (name, country_id, city),
  CONSTRAINT fk_stadiums_country_id
      FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE INDEX idx_stadiums_country ON stadiums(country_id);


# --- !Downs

DROP TABLE IF EXISTS stadiums;