# --- !Ups

CREATE TABLE team_types (
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100) NOT NULL,
    CONSTRAINT pk_team_types PRIMARY KEY (id),
    CONSTRAINT uk_tt_name UNIQUE (name)
);

INSERT INTO team_types (name) VALUES
  ('International'),
  ('Domestic'),
  ('Franchise');

CREATE TABLE teams (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name        VARCHAR(100) NOT NULL,
   country_id  BIGINT NOT NULL,
   type_id     SMALLINT NOT NULL,
   CONSTRAINT pk_teams PRIMARY KEY (id),
   CONSTRAINT uk_t_name_country_type UNIQUE (name, country_id, type_id),
   CONSTRAINT fk_teams_country_id
       FOREIGN KEY (country_id) REFERENCES countries (id)
           ON DELETE RESTRICT ON UPDATE RESTRICT,
   CONSTRAINT fk_teams_type_id
       FOREIGN KEY (type_id) REFERENCES team_types (id)
           ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_teams_country_id ON teams(country_id);
CREATE INDEX idx_teams_type_id ON teams(type_id);

# --- !Downs

DROP TABLE IF EXISTS teams;

DROP TABLE IF EXISTS team_types;