# --- !Ups

CREATE TABLE tours (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name        VARCHAR(100) NOT NULL,
   start_time  TIMESTAMP NOT NULL,
   CONSTRAINT pk_tours PRIMARY KEY (id),
   CONSTRAINT uk_t_name_start_time UNIQUE (name, start_time)
);

# --- !Downs

DROP TABLE IF EXISTS tours;