# --- !Ups

CREATE TABLE players (
     id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     name           VARCHAR(50) NOT NULL,
     country_id     BIGINT NOT NULL,
     date_of_birth  DATE,
     image          VARCHAR(255) NOT NULL,
     CONSTRAINT pk_players PRIMARY KEY (id),
     CONSTRAINT uk_p_name_country_dob UNIQUE (country_id, name, date_of_birth),
     CONSTRAINT fk_players_country_id
         FOREIGN KEY (country_id) REFERENCES countries (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_players_country_id ON players(country_id);

# --- !Downs

DROP TABLE IF EXISTS players;