# --- !Ups

CREATE TABLE series_types (
  id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name    VARCHAR(50) NOT NULL,
  CONSTRAINT pk_series_types PRIMARY KEY (id),
  CONSTRAINT uk_st_name UNIQUE (name)
);

INSERT INTO series_types (name) VALUES
    ('Bilateral'),
    ('Tri series'),
    ('Tournament');


CREATE TABLE game_types (
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(50) NOT NULL,
    CONSTRAINT pk_game_types PRIMARY KEY (id),
    CONSTRAINT uk_gt_name UNIQUE (name)
);

INSERT INTO game_types (name) VALUES
  ('ODI'),
  ('Test'),
  ('T20');


CREATE TABLE series (
    id               integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(100) NOT NULL,
    home_country_id  BIGINT NOT NULL,
    tour_id          BIGINT NOT NULL,
    type_id          SMALLINT NOT NULL,
    game_type_id     SMALLINT NOT NULL,
    start_time       TIMESTAMP NOT NULL,
    CONSTRAINT pk_series PRIMARY KEY (id),
    CONSTRAINT uk_s_name_tour_game_type UNIQUE (name, tour_id, game_type_id),
    CONSTRAINT fk_series_home_country
        FOREIGN KEY (home_country_id) REFERENCES countries (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_series_tour
        FOREIGN KEY (tour_id) REFERENCES tours (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_series_type
        FOREIGN KEY (type_id) REFERENCES series_types (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_series_game_type
        FOREIGN KEY (game_type_id) REFERENCES game_types (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_series_home_country ON series(home_country_id);
CREATE INDEX idx_series_tour ON series(tour_id);
CREATE INDEX idx_series_type ON series(type_id);
CREATE INDEX idx_series_game_type ON series(game_type_id);


CREATE TABLE series_teams_map (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  series_id  integer NOT NULL,
  team_id    BIGINT NOT NULL,
  CONSTRAINT pk_series_teams_map PRIMARY KEY (id),
  CONSTRAINT uk_series_team UNIQUE (series_id, team_id),
  CONSTRAINT fk_series_teams_map_series
      FOREIGN KEY (series_id) REFERENCES series (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_series_teams_map_team
      FOREIGN KEY (team_id) REFERENCES teams (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_series_teams_map_series ON series_teams_map(series_id);
CREATE INDEX idx_series_teams_map_team ON series_teams_map(team_id);

CREATE TABLE man_of_the_series (
   id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   series_id  integer NOT NULL,
   player_id  BIGINT NOT NULL,
   CONSTRAINT pk_man_of_the_series PRIMARY KEY (id),
   CONSTRAINT uk_mots_series_player UNIQUE (series_id, player_id),
   CONSTRAINT fk_mots_series
       FOREIGN KEY (series_id) REFERENCES series (id)
           ON DELETE RESTRICT ON UPDATE RESTRICT,
   CONSTRAINT fk_mots_player
       FOREIGN KEY (player_id) REFERENCES players (id)
           ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_mots_series ON man_of_the_series(series_id);
CREATE INDEX idx_mots_player ON man_of_the_series(player_id);

# --- !Downs

DROP TABLE IF EXISTS man_of_the_series;
DROP TABLE IF EXISTS series_teams_map;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS game_types;
DROP TABLE IF EXISTS series_types;