# --- !Ups

CREATE TABLE tags (
  id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name    VARCHAR(100) NOT NULL,
  CONSTRAINT pk_tags PRIMARY KEY (id),
  CONSTRAINT uk_ta_name UNIQUE (name)
);

INSERT INTO tags (name) VALUES
    ('WORLD_CUP'),
    ('IPL'),
    ('CHAMPIONS_TROPHY'),
    ('BBL'),
    ('ILT20'),
    ('CHAMPIONS_LEAGUE'),
    ('ASIA_CUP'),
    ('WTC');

INSERT INTO tags (name) VALUES
    ('FINAL'),
    ('SEMI_FINAL'),
    ('QUARTER_FINAL'),
    ('KNOCKOUT'),
    ('ELIMINATOR'),
    ('THIRD_PLACE'),
    ('QUALIFIER');


CREATE TABLE tags_map (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  entity_type  VARCHAR(100) NOT NULL,
  entity_id    INTEGER NOT NULL,
  tag_id       SMALLINT NOT NULL,
  CONSTRAINT pk_tags_map PRIMARY KEY (id),
  CONSTRAINT uk_tm_type_id_tag UNIQUE (entity_type, entity_id, tag_id),
  CONSTRAINT fk_tm_tag
      FOREIGN KEY (tag_id) REFERENCES tags (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_tags_map_tag_id ON tags_map(tag_id);

# --- !Downs

DROP TABLE IF EXISTS tags_map;

DROP TABLE IF EXISTS tags;