# --- !Ups

CREATE TABLE result_types (
  id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name    VARCHAR(100) NOT NULL,
  CONSTRAINT pk_result_types PRIMARY KEY (id),
  CONSTRAINT uk_rt_name UNIQUE (name)
);

INSERT INTO result_types (name) VALUES
    ('Normal'),
    ('Tie'),
    ('Draw'),
    ('Super Over'),
    ('Washed Out'),
    ('Bowl Out'),
    ('Forfeit'),
    ('Least Wickets'),
    ('Boundary Count');


CREATE TABLE win_margin_types (
  id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name    VARCHAR(50) NOT NULL,
  CONSTRAINT pk_win_margin_types PRIMARY KEY (id),
  CONSTRAINT uk_wmt_name UNIQUE (name)
);

INSERT INTO win_margin_types (name) VALUES
    ('Run'),
    ('Wicket');


CREATE TABLE matches (
     id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     series_id           BIGINT NOT NULL,
     team_1_id           BIGINT NOT NULL,
     team_2_id           BIGINT NOT NULL,
     toss_winner_id      BIGINT,
     bat_first_id        BIGINT,
     result_type_id      SMALLINT NOT NULL,
     winner_id           BIGINT,
     win_margin          SMALLINT,
     win_margin_type_id  SMALLINT,
     stadium_id          BIGINT NOT NULL,
     start_time          TIMESTAMP NOT NULL,
     is_official         BOOLEAN NOT NULL DEFAULT TRUE,
     CONSTRAINT pk_matches PRIMARY KEY (id),
     CONSTRAINT uk_m_stadium_start UNIQUE (stadium_id, start_time),
     CONSTRAINT fk_m_series
         FOREIGN KEY (series_id) REFERENCES series (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_team_1
         FOREIGN KEY (team_1_id) REFERENCES teams (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_team_2
         FOREIGN KEY (team_2_id) REFERENCES teams (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_toss_winner
         FOREIGN KEY (toss_winner_id) REFERENCES teams (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_bat_first
         FOREIGN KEY (bat_first_id) REFERENCES teams (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_result_type
         FOREIGN KEY (result_type_id) REFERENCES result_types (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_winner
         FOREIGN KEY (winner_id) REFERENCES teams (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_win_margin_type
         FOREIGN KEY (win_margin_type_id) REFERENCES win_margin_types (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT,
     CONSTRAINT fk_m_stadium
         FOREIGN KEY (stadium_id) REFERENCES stadiums (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_matches_series_id ON matches(series_id);
CREATE INDEX idx_matches_team_1_id ON matches(team_1_id);
CREATE INDEX idx_matches_team_2_id ON matches(team_2_id);
CREATE INDEX idx_matches_toss_winner_id ON matches(toss_winner_id);
CREATE INDEX idx_matches_bat_first_id ON matches(bat_first_id);
CREATE INDEX idx_matches_result_type_id ON matches(result_type_id);
CREATE INDEX idx_matches_winner_id ON matches(winner_id);
CREATE INDEX idx_matches_win_margin_type_id ON matches(win_margin_type_id);
CREATE INDEX idx_matches_stadium_id ON matches(stadium_id);


CREATE TABLE match_player_map (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  match_id   INTEGER NOT NULL,
  player_id  BIGINT NOT NULL,
  team_id    BIGINT NOT NULL,
  CONSTRAINT pk_match_player_map PRIMARY KEY (id),
  CONSTRAINT uk_mpm_match_player_team UNIQUE (match_id, player_id, team_id),
  CONSTRAINT fk_mpm_match
      FOREIGN KEY (match_id) REFERENCES matches (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mpm_player
      FOREIGN KEY (player_id) REFERENCES players (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mpm_team
      FOREIGN KEY (team_id) REFERENCES teams (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_match_player_map_match_id ON match_player_map(match_id);
CREATE INDEX idx_match_player_map_team_id ON match_player_map(team_id);
CREATE INDEX idx_match_player_map_player_id ON match_player_map(player_id);


CREATE TABLE dismissal_modes (
 id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 name    VARCHAR(30),
 CONSTRAINT pk_dismissal_modes PRIMARY KEY (id),
 CONSTRAINT uk_dm_name UNIQUE (name)
);

INSERT INTO dismissal_modes (name) VALUES
   ('Bowled'),
   ('Caught'),
   ('LBW'),
   ('Run Out'),
   ('Stumped'),
   ('Hit Twice'),
   ('Hit Wicket'),
   ('Obstructing the Field'),
   ('Timed Out'),
   ('Retired Hurt'),
   ('Handled the Ball');


CREATE TABLE batting_scores (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_id    INTEGER NOT NULL,
    runs               SMALLINT NOT NULL DEFAULT 0,
    balls              SMALLINT NOT NULL DEFAULT 0,
    fours              SMALLINT NOT NULL DEFAULT 0,
    sixes              SMALLINT NOT NULL DEFAULT 0,
    dismissal_mode_id  SMALLINT,
    bowler_id          INTEGER,
    innings            SMALLINT NOT NULL,
    number             SMALLINT,
    CONSTRAINT pk_batting_scores PRIMARY KEY (id),
    CONSTRAINT uk_bs_match_player_innings UNIQUE (match_player_id, innings),
    CONSTRAINT fk_bs_match_player
        FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_bs_dismissal_mode
        FOREIGN KEY (dismissal_mode_id) REFERENCES dismissal_modes (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_bs_bowler
        FOREIGN KEY (bowler_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_batting_scores_match_player_id ON batting_scores(match_player_id);
CREATE INDEX idx_batting_scores_dismissal_mode_id ON batting_scores(dismissal_mode_id);
CREATE INDEX idx_batting_scores_bowler_id ON batting_scores(bowler_id);


CREATE TABLE bowling_figures (
     id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     match_player_id  INTEGER NOT NULL,
     balls            SMALLINT DEFAULT 0,
     maidens          SMALLINT DEFAULT 0,
     runs             SMALLINT DEFAULT 0,
     wickets          SMALLINT DEFAULT 0,
     innings          SMALLINT NOT NULL,
     CONSTRAINT pk_bowling_figures PRIMARY KEY (id),
     CONSTRAINT uk_bf_match_player_innings UNIQUE (match_player_id, innings),
     CONSTRAINT fk_bf_match_player
         FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
             ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_bowling_figures_match_player_id ON bowling_figures(match_player_id);


CREATE TABLE fielder_dismissals (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score_id         INTEGER NOT NULL,
    match_player_id  INTEGER NOT NULL,
    CONSTRAINT pk_fielder_dismissals PRIMARY KEY (id),
    CONSTRAINT uk_fd_score_player_team UNIQUE (score_id, match_player_id),
    CONSTRAINT fk_fd_score
        FOREIGN KEY (score_id) REFERENCES batting_scores (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_fd_match_player
        FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_fielder_dismissals_score_id ON fielder_dismissals(score_id);
CREATE INDEX idx_fielder_dismissals_match_player_id ON fielder_dismissals(match_player_id);


CREATE TABLE extras_types (
  id      SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name    VARCHAR(100) NOT NULL,
  CONSTRAINT pk_extras_types PRIMARY KEY (id),
  CONSTRAINT uk_et_name UNIQUE (name)
);

INSERT INTO extras_types (name) VALUES
    ('Bye'),
    ('Leg Bye'),
    ('Wide'),
    ('No Ball'),
    ('Penalty');


CREATE TABLE extras (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id         INTEGER NOT NULL,
    type_id          SMALLINT NOT NULL,
    runs             SMALLINT NOT NULL,
    batting_team_id  BIGINT NOT NULL,
    bowling_team_id  BIGINT NOT NULL,
    innings          SMALLINT NOT NULL,
    CONSTRAINT pk_extras PRIMARY KEY (id),
    CONSTRAINT uk_e_match_type_batting_innings UNIQUE (match_id, type_id, batting_team_id, innings),
    CONSTRAINT fk_e_match
        FOREIGN KEY (match_id) REFERENCES matches (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e_type
        FOREIGN KEY (type_id) REFERENCES extras_types (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e_batting_team
        FOREIGN KEY (batting_team_id) REFERENCES teams (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e_bowling_team
        FOREIGN KEY (bowling_team_id) REFERENCES teams (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_extras_match_id ON extras(match_id);
CREATE INDEX idx_extras_type_id ON extras(type_id);
CREATE INDEX idx_extras_batting_team_id ON extras(batting_team_id);
CREATE INDEX idx_extras_bowling_team_id ON extras(bowling_team_id);


CREATE TABLE captains (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  match_player_id  INTEGER NOT NULL,
  CONSTRAINT pk_captains PRIMARY KEY (id),
  CONSTRAINT uk_c_match_player UNIQUE (match_player_id),
  CONSTRAINT fk_c_match_player
      FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_captains_match_player_id ON captains(match_player_id);


CREATE TABLE wicket_keepers (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_id  INTEGER NOT NULL,
    CONSTRAINT pk_wicket_keepers PRIMARY KEY (id),
    CONSTRAINT uk_wk_match_player UNIQUE (match_player_id),
    CONSTRAINT fk_wk_match_player
        FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_wicket_keepers_match_player_id ON wicket_keepers(match_player_id);


CREATE TABLE man_of_the_match (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  match_player_id  INTEGER NOT NULL,
  CONSTRAINT pk_man_of_the_match PRIMARY KEY (id),
  CONSTRAINT uk_motm_match_player UNIQUE (match_player_id),
  CONSTRAINT fk_motm_match_player
      FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
          ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_man_of_the_match_match_player_id ON man_of_the_match(match_player_id);

CREATE TABLE totals (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id  INTEGER NOT NULL,
    team_id   BIGINT NOT NULL,
    runs      SMALLINT NOT NULL,
    wickets   SMALLINT NOT NULL,
    balls     SMALLINT NOT NULL,
    innings   SMALLINT NOT NULL,
    CONSTRAINT pk_totals PRIMARY KEY (id),
    CONSTRAINT uk_t_match_team_innings UNIQUE (match_id, team_id, innings),
    CONSTRAINT fk_totals_match_id
        FOREIGN KEY (match_id) REFERENCES matches (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_totals_team_id
        FOREIGN KEY (team_id) REFERENCES teams (id)
            ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_totals_match_id ON totals(match_id);
CREATE INDEX idx_totals_team_id ON totals(team_id);

# --- !Downs

DROP TABLE IF EXISTS totals;
DROP TABLE IF EXISTS man_of_the_match;
DROP TABLE IF EXISTS wicket_keepers;
DROP TABLE IF EXISTS captains;
DROP TABLE IF EXISTS extras;
DROP TABLE IF EXISTS extras_types;
DROP TABLE IF EXISTS fielder_dismissals;
DROP TABLE IF EXISTS bowling_figures;
DROP TABLE IF EXISTS batting_scores;
DROP TABLE IF EXISTS dismissal_modes;
DROP TABLE IF EXISTS match_player_map;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS win_margin_types;
DROP TABLE IF EXISTS result_types;